            IN 02H; ACCPET INPUT FROM INPORT PORT2
            RAR;    SHIFT THE ACCUMULATOR RIGHT
            JM ASCIIYES;     Jump IF  S FLAG IS SET
            JZ ASCIINO;      Jump IF  Z FLAG IS SET
            HLT
ASCIIYES:   MVI A 00H; SET ACCUMULATOR TO ZERO
            MVI A 39H; SET ACCUMULATOR TO ASCIIYES
            OUT 02H
            HLT
ASCIINO:    MVI A 00H; SET ACCUMULATOR TO ZERO
            MVI A 40H; SET ACCUMULATOR TO ASCIINO
            OUT 02H
            HLT